version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb_walle
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: .
    container_name: walle_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/walle_db
      - TZ=America/Guatemala
    depends_on:
      - db
    restart: always

  # <-- NUEVO CONTENEDOR FRONTEND -->
  frontend:
    build: ./frontend
    container_name: walle_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data: